### ISSUE TITLE
Binder notebook doesn't work properly as it has no installation instruction

### ISSUE THREAD

**Issue by MridulS** [llorracc/BufferStockTheory#1]
The binder of the ipython notebook https://mybinder.org/v2/gh/llorracc/BufferStockTheory/master?filepath=Code%2FPython%2FBufferStockTheory.ipynb will build successfully but HARK isn't installed in the docker image as there is no requirements.py file in BufferStockTheory, we need to add one to BufferStockTheory and all other REMARKs

**Comment by llorracc** [comment]
fixed
